# Generated by Django 3.1.2 on 2020-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_auto_20201025_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia'), (1, 'Horror'), (4, 'Dramat')], default=0),
        ),
    ]
